// Code generated by mockery v2.52.2. DO NOT EDIT.

package mocks

import (
	dto "auth/internal/dto"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// AuthUsecase is an autogenerated mock type for the AuthUsecase type
type AuthUsecase struct {
	mock.Mock
}

// Disable2FA provides a mock function with given fields: ctx, email
func (_m *AuthUsecase) Disable2FA(ctx context.Context, email string) error {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for Disable2FA")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, email)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Enable2FA provides a mock function with given fields: ctx, email
func (_m *AuthUsecase) Enable2FA(ctx context.Context, email string) error {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for Enable2FA")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, email)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Enabled2FA provides a mock function with given fields: ctx, email
func (_m *AuthUsecase) Enabled2FA(ctx context.Context, email string) (bool, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for Enabled2FA")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, email)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GenerateOTPSecret provides a mock function with given fields: ctx, email
func (_m *AuthUsecase) GenerateOTPSecret(ctx context.Context, email string) (string, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GenerateOTPSecret")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, email)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Login provides a mock function with given fields: ctx, email, password
func (_m *AuthUsecase) Login(ctx context.Context, email string, password string) (*dto.Tokens, error) {
	ret := _m.Called(ctx, email, password)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 *dto.Tokens
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*dto.Tokens, error)); ok {
		return rf(ctx, email, password)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *dto.Tokens); ok {
		r0 = rf(ctx, email, password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.Tokens)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, email, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LoginOTP provides a mock function with given fields: ctx, email, otp
func (_m *AuthUsecase) LoginOTP(ctx context.Context, email string, otp string) (*dto.Tokens, error) {
	ret := _m.Called(ctx, email, otp)

	if len(ret) == 0 {
		panic("no return value specified for LoginOTP")
	}

	var r0 *dto.Tokens
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*dto.Tokens, error)); ok {
		return rf(ctx, email, otp)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *dto.Tokens); ok {
		r0 = rf(ctx, email, otp)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.Tokens)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, email, otp)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Logout provides a mock function with given fields: ctx, refreshToken
func (_m *AuthUsecase) Logout(ctx context.Context, refreshToken string) error {
	ret := _m.Called(ctx, refreshToken)

	if len(ret) == 0 {
		panic("no return value specified for Logout")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, refreshToken)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Refresh provides a mock function with given fields: ctx, refreshToken
func (_m *AuthUsecase) Refresh(ctx context.Context, refreshToken string) (*dto.RefreshTokenResponse, error) {
	ret := _m.Called(ctx, refreshToken)

	if len(ret) == 0 {
		panic("no return value specified for Refresh")
	}

	var r0 *dto.RefreshTokenResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*dto.RefreshTokenResponse, error)); ok {
		return rf(ctx, refreshToken)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *dto.RefreshTokenResponse); ok {
		r0 = rf(ctx, refreshToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.RefreshTokenResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, refreshToken)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Register provides a mock function with given fields: ctx, username, email, password
func (_m *AuthUsecase) Register(ctx context.Context, username string, email string, password string) (*dto.Tokens, error) {
	ret := _m.Called(ctx, username, email, password)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 *dto.Tokens
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (*dto.Tokens, error)); ok {
		return rf(ctx, username, email, password)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) *dto.Tokens); ok {
		r0 = rf(ctx, username, email, password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.Tokens)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, username, email, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdatePassword2FA provides a mock function with given fields: ctx, email, oldPassword, newPassword, otp
func (_m *AuthUsecase) UpdatePassword2FA(ctx context.Context, email string, oldPassword string, newPassword string, otp string) error {
	ret := _m.Called(ctx, email, oldPassword, newPassword, otp)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePassword2FA")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string) error); ok {
		r0 = rf(ctx, email, oldPassword, newPassword, otp)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ValidateOTP provides a mock function with given fields: ctx, email, otp
func (_m *AuthUsecase) ValidateOTP(ctx context.Context, email string, otp string) (bool, error) {
	ret := _m.Called(ctx, email, otp)

	if len(ret) == 0 {
		panic("no return value specified for ValidateOTP")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (bool, error)); ok {
		return rf(ctx, email, otp)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = rf(ctx, email, otp)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, email, otp)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ValidateToken provides a mock function with given fields: ctx, token
func (_m *AuthUsecase) ValidateToken(ctx context.Context, token string) (string, string, error) {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for ValidateToken")
	}

	var r0 string
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, string, error)); ok {
		return rf(ctx, token)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, token)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) string); ok {
		r1 = rf(ctx, token)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(ctx, token)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// NewAuthUsecase creates a new instance of AuthUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthUsecase {
	mock := &AuthUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
